v1rbox/discox

README.md

Added some documentation on adding commands

Wrote some basic documentation

---

README.md

Simple instructions on how to start the bot.

Added Installation Instructions

---

bot/commands/distrorole.py

Fixes index out of range issue when improperly using `distro add` and `distro remove` commands.

[commands]Adding fix for improper argument amount

---

bot/__main__.py
bot/base.py
bot/logger.py

Added method documentation to following files (will do all of them don't worry):
- `bot.__main__.py`
- `bot/base.py`
Added `debug` and `info` method in `bot/logger.py` for more beautiful prints, with a `get_time` function, I'm not sure what you americans use to format time and date, so change it if I did wrong

Added documentation and lisibility to some code

---

bot/commands/leet_code_problem.py

Leet Code problem command was handling a case when no of arguments was 0, with the updated code the check condition is removed and substituted with a "info" arguments that shows some metadata.

Added info command in leet_code_problem.py

---

bot/commands/distrorole.py

Updating distro command to work with argument parser, and added leaderboard subcommand.

[command]Updating distro command to work with argument parser

---

README.md
bot/base.py
bot/category.py
bot/config.py
bot/logger.py
bot/manager.py

Added colours to Embed class in `bot/config.py`, and added my personnal touch, tell me what you think about it.

added some colours and some humour to this code

---

bot/commands/utility/remind.py

Created remind command

---

bot/commands/request/request.py

Nothing so serious. Just a final fix for it

Final version for the request command

---

bot/commands/utility/remind.py

The „New reminder“ message now has a countdown.
The „This is your reminder“ message now has a link to the first message (for context)

Added timestamp and message link to bot messages

---

bot/commands/calc.py

not using any library, so there is a 'calculator' class in calc.py. The command definition itself is at line 138.
Example use:
``v!calc 1 + 9``
Result: ``10``
``v!calc 1 + 2 * 3``
Result: ``7``
``v!calc (1 + 2) * 3``
Result: ``9``
``v!calc 29 + 8(9/2)``
Result: ``65``

add calc cmd 

---

bot/commands/tic_tac_toe.py

Added reactions to the board so that users don't have to look for it, also the board stays even after the game is over

Enhanced the tic-tac-toe command

---

bot/commands/coderoles/add.py
bot/commands/distroroles/add.py

QUICKFIX - customroles

---

bot/__main__.py

Signed-off-by: misilelaboratory <misileminecord@gmail.com>
fix
simple typo error (commad -> command)
when command not found, say error `commad not found`
when command not found, say error `command not found`
Nope

simple fix typo error

---

bot/commands/utility/help.py

Fix help command

---

bot/__main__.py
bot/commands/utility/ping.py
bot/manager.py

Feature
Commands and events now automatically gets updated when saved
You reload the bot every time you wanna change something
You just hit save and it works :D
Not really

Added autoreloads

---

bot/commands/utility/embeds.py
bot/commands/utility/remind.py
bot/logger.py

Bug fix
Title is enough
Bot gives an error when exexuting the emebds command.
The error:
```
type object 'Embed' has no attribute 'Empty'
```
Bot doesn't give an error when exexuting the emebds command.
No
**Does this PR introduce changes to the database?** (What has changed? Did you make sure to setup the create statements in `__main__.py`?)
No
**Other information:**  None

fix type errors and typos

---

bot/commands/levels/leaderboard.py

Bug fix
Added an extra if statement to control if user is None.
There is a None user in the leaderboard.
There is not a None user in the leaderboard.
No
No
**Other information:**  None

goodbye to holy None on the leaderboard

---

bot/__main__.py
bot/commands/utility/remind.py
bot/tasks/reminders.py

Feature
This commits from the PR #42 but I made some changes. (like creating a task for checking reminders)
Also I added the reminder statement to the CREATE_STATEMENTS.
The reminders stop on restart.
The reminders saving to the db.
No.
Yes, the …

Save the reminders to fetch and handle them on start

---

.github/workflows/code_formatting.yml

update
`code_beautifier.yml` run on pull requests and can't submit those beautified back since it don't have permission so I made it on main branch only.
`code_beautifier.yml` runs on pr that it doesn't have access
Pull request will not run code beautifier
No
No

Ignore beautifying in pull requests

---

.github/workflows/code_formatting.yml

Version of add-and-commit was old, so I upgraded the version

Update the version of add-and-commit action

---

bot/commands/levels/leaderboard.py

Fix
changed 5 to 15
No
No
**Other information:**  None

fix description says top 5 but bot sends top 15

---

bot/commands/utility/help.py

Bug fix
Help command crashes when a specific command entered as argument
No
No
**Other information:**  None

fix type error

---

bot/commands/utility/remind.py
bot/tasks/reminders.py

Bug Fix
Updated outdated database code in the remind command.
Changed > to < in reminders task.
Reminder command returns an error.
Reminder task doesn’t compare timestamps correctly.

Reminder Bug Fix

---

bot/commands/distroroles/add.py
bot/commands/distroroles/info.py
bot/commands/distroroles/remove.py

feature
Added distro info command
No
No
**Other information:** I am currently finding a fast solution to get the dominant color from the image. I'll use that for embed color. Currently the embed color is green

Distro info command and typo fixes

---

bot/commands/levels/rank.py

handle none user

---

bot/commands/distroroles/info.py

bug fix, feature
fixed type errors and added *feature that finds the most common color in the picture and sets that as embed color
command doesn't work
command will work
no
no
**Other …

fixed the ultra buggy command and added a new feature*

---

bot/commands/utility/remind.py

if reminder time is lower than 60 seconds, use sleep instead saving to db

---

bot/commands/utility/avatar.py

Feature
Adds a command that returns the avatar of the sender.

Created avatar command

---

bot/commands/utility/avatar.py

Improvement
Updated regEx.
Added error messages for an invalid user id.

Improved avatar command

---

bot/commands/mod/report.py

Typo
Changed “canseled“ to “canceled“

Fixed typo

---

bot/__main__.py
bot/commands/utility/member_count.py

feature
Bot only sends the member count.
Bot sends the increase/decrease count.
No
Yes, I did.

added increase/decrease count to membercount command

---

.gitignore
bot/__main__.py
bot/commands/levels/rank.py
bot/commands/levels/setrank.py
bot/commands/mod/report.py
bot/commands/utility/avatar.py

Feature
Added int type
Added float type
Added bool type
Added member type (Automatically converts argument to member object)
Added types to some commands

Added types to usage

---

bot/__main__.py
bot/commands/levels/rank.py

Bug fix
Added temporary fix for #97
Changed user.avatar to user.display_avatar in the rank command
#97

Temporary bug fix for #97 and avatar bug fix

---

bot/commands/utility/poll.py

Feature
No
No
**Other information:** Embed color changes according to message author's avatar so command can be slow, I can remove that if that frustrates you.

Added poll command

---

bot/category.py

`v!reminder add` is more logical than `v!remind add`.
Same for the `v!remind list`.

Change the reminder prefix to `reminder`

---

bot/commands/levels/__level_generator.py

Bug fix
changed from adding 1 to level now its not going to
level shown in leaderboard and level pic is different by one
should be the same with leaderboard
no
no

removed +1 level

---

bot/events/reaction_add.py

`set_image` support for edited messages

---

bot/commands/games/minesweeper.py

Adds minesweeper!
We cant play minesweeper :(
Now we can play minesweeper :)
Nothing
Nope

[command]Added Minesweeper Command

---

bot/events/reaction_add.py

Beautified

---

bot/commands/games/minesweeper.py

update
if an user interacts with a minesweeper game and if its not his/her game, then warn the user with an ephemeral message
the interaction just fails
bot sends an ephemeral message warning the user
idk what that means but i think no
no
**Other information:**  
none

interaction with the minesweeper game

---

bot/commands/utility/member_count.py

Feature
When executing the membercount command, sends a message if it it 1k or more (stops at 1050)

Added message when count reaches 1k

---

.github/pull_request_template.md

remove extra space in pr template

---

bot/commands/utility/member_count.py

Feature
Bot sends the celebration embed only in case 1000.
Bot sends the celebration embed if server hits next thousand.
No
No

Made the celebration embed in membercount command dynamic

---

bot/commands/utility/version.py
bot/config.py

Feature
Added version command.
Returns the latest three commits and their authors.
This can be useful to check what version the bot has and if newer commits are already working.
**Other Information**
Just ignore the “change“ in config.py Nothing has actually changed there.

Added version command

---

bot/config.py

Bug fix
Some old code was still there even though I made a commit that removed it

Remove outdated code

---

bot/__main__.py

Increased tag length

---

bot/commands/distroroles/add.py

Also Devuan role must be created

Added Devuan to whitelist

---

bot/commands/coderoles/whitelist.py
bot/commands/distroroles/whitelist.py

Change subcommand whitelist to list
Simple rename
Nope
Nope 

Change whitelist command to list

---

bot/events/reaction_add.py

Bug fix
Quick fix to starboard
If reaction (any) count have more than 5 then it would starboard it
It should ignore non star reaction
None
None
**Other information:** 
None

starboard did not ignore non star reactions

---

bot/commands/utility/about.py

Feature
Added a help message to the about command

Added help message to about

---

README.md
bot/category.py
bot/events/reaction_add.py

Bug Fix
Fixed starboard
DE/WM commands restricted to roles channel

Fixed starboard and DE role permissions

---

bot/commands/fun/gen_spam.py

A new type of spamming algorithm, literal_spam
This spamming algorithm spams the given word and chops off the string to the discord send limit

New spamming algorithm: literal_spam

---

bot/events/on_message.py

Feature
Have added the event listener that listens for the message that contains discord message link and send the contents (and up to 4 images attachment) right at the place where the link is mentioned
Nope
Nope

Embed Link and Picture attachment supports

---

bot/commands/utility/version.py

Feature
The version command will either say:
“Up to date with remote“
or “x commits behind remote“

Add message if bot is behind remote repository

---

bot/commands/utility/help.py

Improvement
The help command can now:
get help on categories
get help on commands in categories

Improved help command

---

bot/commands/levels/rank.py

Bug Fix
Fixed the comparison of user ids
Server rank is always wrong
Its fixed
No
Nope

Fixed server rank

---

bot/commands/distroroles/add.py

Doesnt break anything, and desperately needed.

add VirbOS to distro roles

---

bot/commands/desktoproles/add.py

cinamon -> cinnamon
Just a typo error fix
cinamon
cinnamon
Idk

simple typo error fix

---

bot/commands/coderoles/add.py

Adds D as a code role
I added one element `"D"` to the whitelisted code roles array
*D is not a whitelisted code role*
You can add D as one of your code roles
No
I don't think so
https://dlang.org

Add D code role

---

bot/commands/minecraft.py

Quick fix for the previous commit, the indentation on the formatted string makes it look distorted for mobile users, this fixes the issue.

Quickfix for mobile users

---

bot/events/on_message.py

Automates both the `member` role and the `active member` role
These roles are assigned manually
Now discox will assign them automatically. `Active Member` is assigned
if the user sends a message and is level `3` or above, and does not already have the role. `Member` is assigned on the users first message if they dont already have the role.
No
No

Automate Active Member and Member Role

---

bot/base.py
bot/commands/distroroles/info.py
bot/commands/fun/gen_spam.py
bot/commands/fun/gigachad.py
bot/commands/games/minesweeper.py
bot/commands/games/tic_tac_toe.py
bot/commands/leet_code_problem.py
bot/commands/levels/rank.py
bot/commands/levels/setbg.py
bot/commands/levels/setfontcolor.py
bot/commands/mod/request_close.py
bot/commands/polls/create_multiple_option.py
bot/commands/polls/create_truefalse_option.py
bot/commands/request/request.py
bot/commands/request/request_book.py
bot/commands/utility/avatar.py
bot/commands/utility/help.py
bot/commands/utility/member_count.py

Spelling and grammar fixes
I fixed some spelling and English issues that were present in the role choosing menus, and in command descriptions shown in v!help
English issues in role choosing menus and in command descriptions shown in v!help
No more spelling/grammar mistakes yay
No
No

Fix English mistakes in role choosing menus and in command descriptions

---

bot/events/on_message.py

Fix grammatical mistake in role assignment message

---

bot/__main__.py
bot/commands/utility/help.py

Bug Fix
Fixes the help command
**What is the new behavior**

Fixed help command

---

bot/commands/desktoproles/menu.py

**Budgie Desktop was not there**
and **I added it**

Added the Budgie Desktop 

---

bot/commands/desktoproles/menu.py

Fixes QTile being listed twice on the desktop list.

remove Qtile #2

---

bot/category.py

fixes broken permission for presence category

Fixed presence category

---

bot/events/on_message.py

But, don't worry. When someone becomes a active member, it will show an active member, and once they become a member it show "a".
**Mr. NoobCoder made a pr and I really don't know it was merged but the title was literally, changed the a member bug to an member :skull:**

Fixed the an member bug to a member
