bot/commands/distrorole.py

Added distro command, Allows user to self-add to whitelisted distro roles, with max amount of roles per user being set to 3. Roles are cosmetic only.

[command]Added distro command

---

bot/commands/distroroles/add.py

Checks if role exists ignoring capitalization when adding a new role to a user. If a match is found tells user the correct input for it.

Checks if role exists ignoring capitalization

---

bot/commands/distroroles/remove.py

Checks if role exists ignoring capitalization, when removing a role from a user. If a match is found tells the user the correct input for it. If the user does not have the guessed role it will fall to the next if statement.

Checks if role exists ignoring capitalization for removing roles

---

bot/commands/coderoles/add.py
bot/commands/coderoles/remove.py
bot/commands/distroroles/leaderboard.py
bot/commands/distroroles/remove.py

Fix bug where incorrect variable was left in distro leaderboard command,
Added feature to remove distro/code roles from server when empty
distro leaderboard breaks because wrong variable is referenced, distro/code roles remain active on server even when empty
Fixes distro leaderboard, and now code/distro roles are deleted when they have 0 members
No

[command]Added feature to remove role from server when empty

---

bot/commands/coderoles/add.py
bot/commands/coderoles/remove.py
bot/commands/distroroles/add.py
bot/commands/distroroles/remove.py

feature
the PR makes the `distro` and `code` commands case-insensitive
if the user inputs a role name with incorrect capitalization, the bot suggests a role with correct caps
the functions are now case-insensitive
i don't think so
**Other information:**  
also added `UwUntu` to distros

remove case sensitivity in distro and code commands

---

bot/commands/calc.py

If you write a command like "v!calc 2\*2\*2" bot will answer "2*2*2 = **8**".
I escaped the "*" symbol.
2*2*2 = **8**
\>\>\>
2\*2\*2 = **8**

Escape '*' symbol in calc command

---

bot/config.py

Bug fix
Python leaves comma as blank string so int function will error it out
Python throws error on no .env configured
This shouldn't make python complains about empty string and try convert it to integer
None

python does leave comma as empty string

---

poetry.lock
pyproject.toml
requirements.txt

because it used in distro info command

add `colorthief` module

---

bot/commands/games/minesweeper.py

Added a return statement in the clear surroundings to prevent clearing if the button pushed is near a mine

Quickfix For Minesweeper

---

bot/events/on_voice_state.py

Bug fix
Fixed the bug that occurs when moving to "Create VC" from "Voice Channel #x"
Bot doesn't delete the previous channel when moving to "Create VC"
Bot always check the previous channel.
No
No

[fix] always check `before.channel`

---

bot/events/reaction_add.py

Bug fix
Bot can't detect URLs with no parameters.
Bot detects URLs with no parameters.
No
No

Fixed regex not match with parameter-less URLs

---

bot/commands/distroroles/info.py

Bug fix
Bot sends an unhandled error if the API sends internal server error with 200 response.
Bot handles that and simply sends a distro not found error
No
No

Handle if there is an internal server error that sends 200 response code

---

bot/base.py

Update
A typing for Manager class is now added to the base. Should works without seeing circular imports
If you import module directly it will error with circular import
wrapping it in TYPE_CHECKING will import it at checking its type not the runtime
Nope
Nope
**Other information:** 
Nope

since manager is for typing why not wrap it in TYPE_CHECKING

---

bot/commands/fun/gen_spam.py

I just forgot that the discord send limit if 2K even for bots (I though I saw 4K in discox error message somewhere)

Fix discord send limit from 4K to 2K

---

bot/commands/fun/gen_spam.py

Bug fix, feature
Chop in a more intelligent way, instead of chopping in the end of spam limit, it will chop a bit earlier where it meets the final character that is either a space, left/right angle bracket (for emojis), or a new line (just in case)
Chops at the end of discord send limit, which when spammed with emojis, ends up with half emoji strings that discord uses to recognize.
Exactly prevents the above
There may not be any breaking changes but, we need more chop cases and it is good idea to let the users test them

Better chop in literal_spam

---

bot/events/on_raw_reaction_add.py

Feature
Added message content to boost messages.
Boost messages doesn't have a content so boost messages on starboard looks empty.
Boost messages are now handled and the message content is `<booster> boosted the server 😎`.
No
No

Handle boost messages on starboard

---

bot/commands/fun/gen_spam.py

```
v!gen_spam <algo> <message that contains ping>
```
This permits massping of people, here is an example (multiple mentions must be without spaces):
```
v!gen_spam literal_spam @demir@AinTea@silent@Drillenissen
```
Also, here is the conversation with one of the server member that made me make this pull request https://discord.com/channels/1052597660860821604/1056967713299382272/1099010346892660846 (thanks to `demir`)

Fixed a bug that permitted to massping multiple people

---

bot/commands/utility/help.py

Fix
If a command is in a category with no prefix (e. g. gen_spam) the help command will now work

fixed help for commands in categorys with no prefix

---

bot/commands/distroroles/add.py

Added Linux Mint Debian edition to distro roles. I use it myself and it just felt weird that it was missing. Shouldn't break anything.

Add LMDE to distro roles

---

bot/commands/leet_code_problem.py
bot/config.py

Bug fix
- fixed Leetcode command not working
- added getenv function to config.py
(how it is right now)

Fixed Leetcode not working

---

bot/events/on_message.py

The bot used to message "Congratulations {username}! You are now an Member". I have fixed it and now it uses a/an according to the first letter of the role name. Previously the first index of letter was not lowered case and that's why it was not working

Fixed 'an member' instead of 'a member' bug

---

bot/commands/fun/pp.py

add the pp command
the pp command measures the pp of a user or word, literally a dick waving contest
no pp command
pp command
no, only adds more pps
10000x more pps into the database

add pp command

---

bot/commands/distroroles/menu.py

wewduck told me to lol. 
Just added one line to bot/commands/distroroles/menu.py and added qubes to the array
qubes is recognized by distrowatch so any upstream icons should work fine. 
i love qubes os and it is amazing so it is a shame it is not here yet. 
Please merge :O
-tillay8

add qubes os to distro menu
